### ISSUE TITLE
Generated code does not seem to compile

### ISSUE THREAD

**Issue by inthegarage** [sapienstech/typescript-angular2-swagger-codegen#6]
In the generated file DefaultAPI.ts I am getting quite a few errors regarding the instance of check. For instance:

        if (contentPackageId !== undefined) {
            if(contentPackageId instanceof Date) {

Is generated for my yaml file and yet when an attempt to compile this I get:

[INFO] ERROR in src/app/api/DefaultApi.ts (353,16): The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter.
[INFO] src/app/api/DefaultApi.ts (354,79): Property 'd' does not exist on type 'string & Date'.

There are several of these in the file generally regarding a passed in parameter and a check around that parameter to see if it is of type 'Date'.
I have seen the following issue reported here, but that seems very out of date and resolved a long time ago:

https://github.com/Microsoft/TypeScript/issues/2775

As this is generated code, how can I effect the operation and get the code to compile successfully?
I'm using swagger-codegen 2.2.2 maven plugin, with setting:
<language>typescript-angular2</language>

**Comment by briosheje** [comment]
I've got the same issue here: in each api file I can't get over these errors (all seems to be related to instanceof left-hand side being "string" instead of "any" and the next few lines with the .d . All seems to be related with Date checks anyway).

Not sure whether it's related to the typescript version itself (using ~2.1.5 here) or if it's a bug.

**Comment by inthegarage** [comment]
I was using ~2.0.0 which actually equates to 2.0.10. I just tried with the latest 2.2.2 and no change, so this seems to be a bug not a version issue. 
As a functional request, I'd prefer that the app.api and other items was _optional_  and we can choose to just have the models or the models and support software. I'm having to delete half of them at the moment as they are not required in the way we are doing things.

**Comment by inthegarage** [comment]
@briosheje Looks like this is fixed in master and if you do a build of 2.2.3-Snapshot, you get completely different api code. Not ideal, but a better work around.

**Comment by inthegarage** [comment]
@briosheje Yeah confirmed, it's fixed in Master.

**Comment by MTyson** [comment]
Errors everywhere.  Beware.  Time sink.

**Comment by inthegarage** [comment]
This now fixed as 2.2.3 of the swagger plugin is released. If you have this issue, move to 2.2.3.
Closing issue.
